eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      metrics:
        enabled: true # 👈 Activa métricas globales de rutas del Gateway
      routes:
        # --- RUTA PARA ÓRDENES ---
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: ordersCircuitBreaker
                fallbackUri: forward:/fallback/orders

        # --- RUTA PARA USUARIOS (Login/Registro) ---
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**

        # --- RUTA PARA INVENTARIO ---
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/dishes/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: inventoryCircuitBreaker
                fallbackUri: forward:/fallback/dishes

        # --- RUTA PARA PAGOS ---
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/fallback/payments

# Configuración Global de Disyuntores (Resilience4j)
resilience4j:
  circuitbreaker:
    instances:
      ordersCircuitBreaker:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      inventoryCircuitBreaker:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      paymentCircuitBreaker:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      ordersCircuitBreaker:
        timeoutDuration: 2s
      inventoryCircuitBreaker:
        timeoutDuration: 2s
      paymentCircuitBreaker:
        timeoutDuration: 2s

# 📊 CONFIGURACIÓN DE OBSERVABILIDAD (ACTUATOR & PROMETHEUS)
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
