eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        # --- RUTA PARA ÓRDENES ---
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: ordersCircuitBreaker
                fallbackUri: forward:/fallback/orders

        # --- RUTA PARA USUARIOS (Tu nuevo servicio) ---
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/dishes/**   

# Configuración del Disyuntor (Circuit Breaker) para Órdenes
resilience4j:
  circuitbreaker:
    instances:
      ordersCircuitBreaker:
        slidingWindowSize: 6
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      ordersCircuitBreaker:
        timeoutDuration: 2s
