server:
  port: 8081

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/orders_db_prod
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://registry-server:8761/eureka/
