server:
  port: 8084 # 🎯 Cambiado para que no choque con usuarios

spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db_dev?createDatabaseIfNotExist=true # 🎯 Localhost para tu CMD
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # 🎯 Localhost para tu Eureka local
