server:
  port: 8085

spring:
  application:
    name: payment-service # 👈 Debe coincidir con el lb://payment-service del gateway
  datasource:
    # 🔧 CORREGIDO: de localhost:3304 a mysql-db:3306
    url: jdbc:mysql://mysql-db:3306/payments_db_dev?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      # 🔧 CORREGIDO: de localhost a registry-server
      defaultZone: http://registry-server:8761/eureka/

# 📊 CONFIGURACIÓN DE OBSERVABILIDAD (ACTUATOR & PROMETHEUS)
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
